### ISSUE TITLE
TestMirReconfiguration_AddValidatorsOnce is flaky

### ISSUE THREAD

**Issue by dnkolegov** [consensus-shipyard/lotus#77]
Link
https://app.circleci.com/pipelines/github/consensus-shipyard/lotus/129/workflows/fea08497-5488-446f-b7e3-694b788f10d2/jobs/903/steps

Trace
```
2023-02-16T10:29:40.272Z	INFO	mir-consensus	mir/manager.go:284	manager received error:could not process PassiveModule (app) events: app restore state error: RestoreState: validator t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq failed to wait for next block 32: validator t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq context canceled while waiting for a snapshot	{"validator": "t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq"}
2023-02-16T10:29:40.272Z	INFO	mir-consensus	mir/manager.go:342	Mir manager shutting down	{"validator": "t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq"}
2023-02-16T10:29:40.273Z	INFO	mir-consensus	mir/manager.go:359	Network transport stopped	{"validator": "t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq"}
2023-02-16T10:29:40.273Z	INFO	mir-consensus	mir/manager.go:363	Mir manager shut down	{"validator": "t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq"}
2023-02-16T10:29:40.273Z	INFO	mir-consensus	runtime/panic.go:838	Mir manager t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq stopped	{"validator": "t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq"}
panic: validator t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq consensus error: could not process PassiveModule (app) events: app restore state error: RestoreState: validator t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq failed to wait for next block 32: validator t1bfyycwgzqkkp7haslyqahv3l4p6zfl2i3qf7ypq context canceled while waiting for a snapshot

goroutine 6320560 [running]:
github.com/filecoin-project/lotus/chain/consensus/mir.(*Manager).Serve(0xc00d091e00, {0x5a08338?, 0xc031d15a00?})
	/home/circleci/project/chain/consensus/mir/manager.go:286 +0x1765
github.com/filecoin-project/lotus/chain/consensus/mir.Mine({0x5a08338, 0xc031d15a00}, {{0xc00755b9b0?, 0x73fa6d?}}, {0x5a1e700?, 0xc00ababb00?}, {0x5a37dd8?, 0xc00bbf4840?}, {0x5a00d80, 0xc03596c960}, ...)
	/home/circleci/project/chain/consensus/mir/mine.go:28 +0x17d
github.com/filecoin-project/lotus/itests/kit.(*Ensemble).BeginMirMiningWithMembershipFromFile.func1({0x5a08338, 0xc031d15a00}, 0xc031d223f0?, 0xc0099b8900)
	/home/circleci/project/itests/kit/ensemble.go:1182 +0x1f2
created by github.com/filecoin-project/lotus/itests/kit.(*Ensemble).BeginMirMiningWithMembershipFromFile
	/home/circleci/project/itests/kit/ensemble.go:1174 +0x118
```

**Comment by dnkolegov** [comment]
Another failure: https://app.circleci.com/pipelines/github/consensus-shipyard/lotus/204/workflows/5328adc7-26b5-4f50-9de2-9fdf3514c1d0/jobs/1557/steps
```
023-02-25T06:14:28.479Z	INFO	mir-consensus	mir/state_manager.go:485	Getting Cid for block height 181 and cid bafy2bzacebapk7xzjo46m22qpiniri36k5pqkb4znvk7fmyv67dwocquiuhnc to include in snapshot	{"validator": "t1i2e7hkfqyfz2bgkdtnk3ibllcmb4jnbrus336hi"}
2023-02-25T06:14:28.481Z	INFO	mir-consensus	mir/state_manager.go:485	Getting Cid for block height 180 and cid bafy2bzacedg6sfptd2xwdfljook35z3ckqc2qva2qgrujgn4cxlrfhp6tms22 to include in snapshot	{"validator": "t1i2e7hkfqyfz2bgkdtnk3ibllcmb4jnbrus336hi"}
2023-02-25T06:14:28.481Z	INFO	mir-consensus	mir/state_manager.go:492	Snapshot finished: epoch - 34, height - 186	{"validator": "t1i2e7hkfqyfz2bgkdtnk3ibllcmb4jnbrus336hi"}
2023-02-25T06:14:28.481Z	INFO	mir-consensus	mir/state_manager.go:493	Snapshot for epoch 34 finished	{"validator": "t1i2e7hkfqyfz2bgkdtnk3ibllcmb4jnbrus336hi"}
    mir_test.go:437: 
        	Error Trace:	/home/circleci/project/itests/mir_test.go:437
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestMirReconfiguration_AddValidatorsOnce
    mir_test.go:407: [*] defer: cancelling TestMirReconfiguration_AddValidatorsOnce contex
```
